### ISSUE TITLE
Pagination not working across with Models 

### ISSUE THREAD

**Issue by jsahu-wal** [pat/thinking-sphinx#1144] opened 2019-09-18 11:05 UTC
Pagination isn't working properly if searching with two different models.
Below is an example

```ruby
def search
  records = ThinkingSphinx.search(params[:query],
                                    classes:    [Article, Review],
                                    page:       params[:page],
                                    per_page:   params[:per_page] || 25)

  articles = Article.where(id: records.map { |record| record.try(:article_id) } )
  reviews  = Review.where(id: records.map { |record| record.try(:review_id) } )

  render json: { 
    articles: ArticleSerializer.new(articles),
    reviews: ReviewSerializer.new(reviews),
    result_count: records.count 
  }
end
```

### Result without pagination 
```json
{
    "articles": [
        {
            "id": 11,
            "name": "test",
        },
        {
            "id": 13,
            "name": "test s3 11 sep",
        }
    ],
    "reviews": [
        {
            "id": 1,
            "name": "Test Title",
        },
        {
            "id": 4,
            "name": "Test Review",
        }
    ],
    "result_count": 9
}

``` 

### Result with pagination: 
**per_page:2, page: 1** 
```json
{
    "articles": [],
    "reviews": [
        {
            "id": 1,
            "name": "Test Title",
        },
        {
            "id": 4,
            "name": "Test Review",
        }
    ],
    "result_count": 9
}
```

### Result with pagination: 
**per_page:2, page: 2** 
```json
{
    "articles": [
        {
            "id": 11,
            "name": "test",
        }
    ],
    "reviews": [],
    "result_count": 9
}

```

### Result with pagination: 
**per_page:2, page: 3** 
```json
{
    "articles": [
        {
            "id": 13,
            "name": "test s3 11 sep",
        }
    ],
    "reviews": [],
    "result_count": 9
}

```

So technically, there should be no page number 3.
Also, records are not fetching as expected.

**Comment by pat** [comment] 2019-09-29 04:12
Hmm, this is an odd one.

I guess as a starting point for debugging… do the logs suggest the right number of records are being returned? You'll see a query to Sphinx (via a SphinxQL statement - which looks very similar to SQL), and then corresponding queries to your database for both Articles and/or Reviews (depending if both are in the page of results).

Also, you can avoid double-requests for the model instances. Instead of the following:

```ruby
articles = Article.where(id: records.map { |record| record.try(:article_id) } )
reviews  = Review.where(id: records.map { |record| record.try(:review_id) } )
```

Try this instead - as each record should already be the appropriate ActiveRecord instance:

```ruby
articles = records.select { |record| record.is_a?(Article) }
reviews = records.select { |record| record.is_a?(Review) }
```

**Comment by pat** [comment] 2019-11-14 07:16
Closing this as there's been no comments in over a month - but certainly, if it remains an issue do let me know and we can keep trying to figure out the cause.

**Closed by pat** 2019-11-14 07:16 UTC
