### ISSUE TITLE
Conditions under which the index updates

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#974] opened 2016-04-06 15:03 UTC
We're using assign_attributes and save on a record. There is a ts-sidekiq-delta sidekiq job that kicks off, but the index isn't updated. Are there conditions under which the index won't be updated? One attribute that has changed isn't updating in the index.

```ruby
ThinkingSphinx::Index.define :ticket, with: :active_record, delta: ThinkingSphinx::Deltas::SidekiqDelta do
  has status_id
end
```

```ruby
create_table "tickets", force: :cascade do |t|
    t.boolean  "delta",                               default: true,  null: false
end
```

The status_id has changed, but searching doesn't return the correct results unless `rake ts:index` is run.

Also, should there be two instances of searchd running?

**Comment by pat** [comment] 2016-04-06 23:19
Hi Adam, just want to clarify the situation further:

* Are other fields/attributes updating as expected?
* Is the issue happening locally, or only in production? If it's locally, are you seeing the SphinxQL statement in the Rails logs when the sidekiq job is processed that's updating the record?

The logic around the delta callbacks is pretty simple:
https://github.com/pat/thinking-sphinx/blob/develop/lib/thinking_sphinx/active_record/callbacks/delta_callbacks.rb#L7
https://github.com/pat/thinking-sphinx/blob/develop/lib/thinking_sphinx/active_record/callbacks/delta_callbacks.rb#L23

They're invoked by standard Rails callbacks (before_save to set the delta flag to true, and then after_commit to call out to Sphinx). So, if you're using a non-callback approach to update the record (e.g. `update_column`, `update_columns`, or the bulk `update_all`), nothing will happen. The standard `save`, `create`, and `update_attributes` _will_ fire the callbacks, and thus will persist changes to Sphinx. Within the callbacks, there's a check to see if delta indices actually exist for the model, whether the delta flag is set to true, and whether delta processing is suspended or not (and TS doesn't auto-suspend processing unless you ask it to).

**Comment by atomical** [comment] 2016-04-07 17:18
It only happens on production with tickets created through our API. 
Changing other attributes doesn't update the index as well.

Even after the change in the controller, changing it in the console doesn't update the index even though the sidekiq job runs.

````portal(prod)> t.save
   (0.4ms)  BEGIN
  SQL (0.5ms)  UPDATE `tickets` SET `status_id` = 3, `updated_at` = '2016-04-07 16:59:47' WHERE `tickets`.`id` = 358973
   (6.6ms)  COMMIT
=> true
````

```
2016-04-07T17:13:46Z 8521 TID-149jdo ThinkingSphinx::Deltas::SidekiqDelta::DeltaJob JID-4c2674c65685e9ebfcda0cad INFO: start
Sphinx 2.2.6-id64-release (r4843)
Copyright (c) 2001-2014, Andrew Aksyonoff
Copyright (c) 2008-2014, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/var/www/shared/config/production.sphinx.conf'...
WARNING: key 'enable_star' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'enable_star' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'enable_star' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'enable_star' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'enable_star' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: 80 more warnings skipped.
indexing index 'ticket_delta'...
collected 117 docs, 0.0 MB
collected 0 attr values
sorted 0.0 Mvalues, 100.0% done
sorted 0.0 Mhits, 100.0% done
total 117 docs, 31854 bytes
total 0.046 sec, 689152 bytes/sec, 2531.26 docs/sec
total 125 reads, 0.000 sec, 1.4 kb/call avg, 0.0 msec/call avg
total 12 writes, 0.000 sec, 24.4 kb/call avg, 0.0 msec/call avg
rotating indices: successfully sent SIGHUP to searchd (pid=30617).
2016-04-07T17:13:46Z 8521 TID-149jdo ThinkingSphinx::Deltas::SidekiqDelta::DeltaJob JID-4c2674c65685e9ebfcda0cad INFO: done: 0.071 sec
2016-04-07T17:13:46Z 8521 TID-149jdo ThinkingSphinx::Deltas::SidekiqDelta::FlagAsDeletedJob JID-c562d0b7324949bacb53af7d INFO: start
2016-04-07T17:13:46Z 8521 TID-149jdo ThinkingSphinx::Deltas::SidekiqDelta::FlagAsDeletedJob JID-c562d0b7324949bacb53af7d INFO: done: 0.001 sec
```

**Comment by pat** [comment] 2016-04-10 01:58
To answer your earlier question first: TS v3 configures Sphinx to run in threaded worker mode, which means there'll always be at least two processes (the master, and the first waiting worker).

Also: my earlier comment about a SphinxQL statement for the update was wrong - that's only for real-time indices, not SQL-backed indices (and you're using the latter).

All that said, I'm really not sure what the cause of the problem is. Can you try firing up a mysql console on production that talks to Sphinx (e.g. something along the lines of `mysql --host 127.0.0.1 --port 9306`) and running a SphinxQL query on both core and delta indices separately to see if the status_id value is correct in either?

`SELECT status_id FROM ticket_core WHERE sphinx_internal_id = TICKETID`
`SELECT status_id FROM ticket_delta WHERE sphinx_internal_id = TICKETID`

**Comment by atomical** [comment] 2016-04-10 02:38
```mysql> SELECT status_id FROM ticket_core WHERE sphinx_internal_id = 359235;
+-----------+
| status_id |
+-----------+
|         1 |
+-----------+
1 row in set (0.00 sec)

mysql> SELECT status_id FROM ticket_delta WHERE sphinx_internal_id = 359235;
+-----------+
| status_id |
+-----------+
|         3 |
+-----------+```


The query for filtering:
```sql
mysql> SELECT * FROM `ticket_core`, `ticket_delta` WHERE `status_id` IN (1) AND `sphinx_deleted` = 0 AND `sphinx_internal_id` = 359235 ORDER BY `id` desc;
# returns one record
```

```ruby
(prod)> Ticket.search( with: {sphinx_internal_id: 359235, status_id: 3})
  Sphinx Query (1.1ms)  SELECT * FROM `ticket_core`, `ticket_delta` WHERE `sphinx_internal_id` = 359235 AND `status_id` = 3 AND `sphinx_deleted` = 0 LIMIT 0, 20
  Sphinx  Found 1 results
```

```ruby
(prod)> Ticket.search( with: {sphinx_internal_id: 359235, status_id: 1})
  Sphinx Query (0.8ms)  SELECT * FROM `ticket_core`, `ticket_delta` WHERE `sphinx_internal_id` = 359235 AND `status_id` = 1 AND `sphinx_deleted` = 0 LIMIT 0, 20
  Sphinx  Found 1 results
```

Should search index core and delta?

**Comment by pat** [comment] 2016-04-10 03:04
So the delta record has the correct status id (3?), but the core record isn't having sphinx_deleted set to 1, it seems? Though the FlagAsDeletedJob is being processed…

Which versions of thinking-sphinx and ts-sidekiq-delta are you using?

**Comment by atomical** [comment] 2016-04-10 03:09
Correct. The status_id should be 3.

thinking-sphinx (3.1.4)
ts-sidekiq-delta (0.2.0)

**Comment by pat** [comment] 2016-04-10 03:12
Hmm, okay. Can you confirm that the record is actually marked as not deleted?

`SELECT sphinx_deleted FROM ticket_core WHERE sphinx_internal_id = 359235`

**Comment by atomical** [comment] 2016-04-10 03:14
```mysql> SELECT sphinx_deleted FROM ticket_core WHERE sphinx_internal_id = 359235
    -> ;
+----------------+
| sphinx_deleted |
+----------------+
|              0 |
+----------------+```

**Comment by pat** [comment] 2016-04-10 06:17
Well I'm struggling to think of why this is happening…

Adam, could you run some more tests - what I'm curious about is whether sphinx_deleted is being set to 1 when you update other columns in a model, as opposed to only status_id. Also, you mentioned you're only seeing this problem when the change is made via your API - is everything fine when you make the change through the console instead?

**Comment by atomical** [comment] 2016-04-12 20:59
I changed some other fields and sphinx_deleted isn't being set to 1 in the core.

 It looks like it might be a race condition.

```
mysql> SELECT id,sphinx_internal_id, status_id,sphinx_deleted FROM ticket_core WHERE sphinx_internal_id = 360137;
+----------+--------------------+-----------+----------------+
| id       | sphinx_internal_id | status_id | sphinx_deleted |
+----------+--------------------+-----------+----------------+
| 46097572 |             360137 |         1 |              0 |
+----------+--------------------+-----------+----------------+
```

When I run `touch` on the record in the rails console it shows this in the Sidekiq console:
```
ThinkingSphinx::Deltas::SidekiqDelta::FlagAsDeletedJob	["ticket_core", 46097571]
```

So it looks like it's off by one! By the way the record 46097571 doesn't exist in the sphinx database.

**Comment by pat** [comment] 2016-04-12 23:30
That's certainly useful information! How many Sphinx indices do you have defined in your system? Is there any conditional logic around the number of indices?

That document id is calculated from the primary key with an offset to ensure they're globally unique (not just within a specific index), and that's based on the number of indices and the position of that specific index in the list of indices… so it's sounding like that calculation is providing different values at different points.

**Comment by atomical** [comment] 2016-04-12 23:48
We have 43 files in the indices directory. One of them isn't using the sidekiq gem for deltas.

**Comment by pat** [comment] 2016-04-12 23:52
The fact that one isn't using deltas shouldn't have an impact, but just in case - the offset calculation is based on alphabetical order - is the model in question before Ticket from an alphabetical order perspective? Are there any models between that and Ticket where deltas work fine?

**Comment by atomical** [comment] 2016-04-14 13:05
It appears the issue was that we had an index that wasn't named properly. It didn't have _index on the end of the filename and it didn't have the delta option set. We were manually calling indexer with that specific index. There may have been a disparity with the index count in different threads and processes.

**Comment by pat** [comment] 2016-04-14 14:24
Was the filename the same as the model in question? (i.e. `app/indices/ticket.rb`) I've seen that make Rails get confused in the past…

But things are working well now for you?

**Closed** 2016-05-13 01:56 UTC
Labels: discussion
