### ISSUE TITLE
Multi-tenancy with Apartment and NoIndicesError

### ISSUE THREAD

**Issue by chickenboot** [pat/thinking-sphinx#1018] opened 2016-10-17 10:45 UTC
I've recently done a bunch of work to turn a production Rails (successfully using thinking sphinx) app to multi-tenanted from single-tenanted, and am at a stage where everything is running well bar this problem. 

I'm setup in roughly the same way as the final comment in this discussion (https://github.com/pat/thinking-sphinx/issues/854), using delta-indexing, and indexing, delta-indexing and searching works a treat on tenants with existing data.

The problem comes on creation of a new Account (and a new schema) - the account creation works fine, but trying to create the first record for any indexed model throws `ThinkingSphinx::NoIndicesError`. I'm assuming this is because the actual index files don't yet exist, so I tried to fix this by injecting some dummy data into each table on account creation and spawning a `rake ts:index`, but this still doesn't work until I restart my server (I think the list of index files is cached?). I am looking at monkey patching for now (by finding the cached index list and resetting it on account creation), but was wondering if there was a simpler fix or if I've just setup incorrectly. I'm using thinking-sphinx 3.1.4 and apartment 1.2.0.

**Comment by pat** [comment] 2016-10-18 01:06
You're right, the loaded indices are cached. You can get around this by running the following code:

```ruby
ThinkingSphinx::Configuration.reset
```

However, this will also mean any changes you've made to the singleton instance of `ThinkingSphinx::Configuration` will be lost - namely, the `index_set_class`, so make sure you set that again as well.

Once you've got the new index set, then you'll want to re-render the configuration file, index the newly defined indices, and then restart Sphinx. So, the full code might end up looking something more like the following:

```ruby
ThinkingSphinx::Configuration.reset
configuration = ThinkingSphinx::Configuration.instance
configuration.index_set_class = IndexSet
configuration.render_to_file

# Then process just the new indices - you don't need dummy data in the tables:
configuration.controller.index 'user_tenant1_core', 'user_tenant1_delta'
# Restart Sphinx so it's aware of the new indices:
configuration.controller.stop
configuration.controller.start
# or, perhaps replace the previous two lines with a call to the ts:restart rake task
# instead. More overhead, but better edge case handling.
```

**Comment by pat** [comment] 2016-10-18 01:06
The above code was suggested without testing, though - so certainly make sure this is behaving as you need it to!

**Comment by chickenboot** [comment] 2016-10-18 11:23
Hi Pat,

Thanks for such a quick, comprehensive response!

I tested this this morning – it didn't work straight out of the box: the sphinx configuration file that was generated in `configuration.render_to_file` didn't have any indices in it. Drilling down a bit, it looks like the cause of this is inside `preload_indices` in `ThinkingSphinx::Configuration` – because the index definitions are already loaded in memory, the line:

```ruby
ActiveSupport::Dependencies.require_or_load file
```
Doesn't load the indexes, and I think that means the list of indices is empty. I've monkey patched this to the following (with a bit more context either side):

```ruby
index_paths.each do |path|
  Dir["#{path}/**/*.rb"].sort.each do |file|
    ActiveSupport::Dependencies.load_file file
  end
end
```

Everything seems to be working perfectly at first glance, but I will do more testing and let you know if I spot any more problems. Cheers!

**Comment by pat** [comment] 2016-10-18 11:52
Ah, I'd not considered the Ruby/ActiveSupport reloading part of things… great to know you've found the workaround. I'm not yet sure if I want to rejig TS to use `load_file`, but am open to it. I guess I just need to think through the implications of it all…

**Comment by chickenboot** [comment] 2017-01-13 20:12
Hi Pat,

I've found an interesting problem with this approach: without re-indexing, I get duplicate results when I search for something that has since changed (and so is in the delta index) in a tenant that previously existed. I think I've finally tracked it down to a problem with the delta callback. The problem appears to be in the setting of `sphinx_deleted` on the item in the core index (so the search returns the core index result and the delta index result).

The `DeleteJob` creation at `ThinkingSphinx::Deltas::DefaultDelta#delete` uses `ThinkingSphinx::Core::Index#document_id_for_key` to generate the document id to set as deleted:

```ruby
  def document_id_for_key(key)
    key * config.indices.count + offset
  end
```

Obviously `config.indices.count` has changed since the last index, so the wrong document is being marked as deleted – if I manually run the delete job on a key generated with the previous index count, everything works fine.

I wonder if you have an opinion on the best way to work around this – I have some ideas, but there might be a simple way that I'm missing!

**Comment by pat** [comment] 2017-01-14 02:26
I'm keen to hear your ideas Colin, as I can't think of anything simple to work around this at the moment!

**Comment by chickenboot** [comment] 2017-01-16 17:01
I didn't say my ideas were simple...!

I think for us I can rely on the fact that I manage the operations for the app too – we don't re-index without an app restart which makes things a little more straightforward; I was thinking of something like this:

```ruby
class IndexSet < ThinkingSphinx::IndexSet
  def self.new_tenant_reset(tenant)
    indexes = ['xxx', 'yyy', 'zzz']
    ThinkingSphinx::Configuration.instance.update_index_counts!
    pre_index_counts = ThinkingSphinx::Configuration.instance.tenanted_index_count

    ThinkingSphinx::Configuration.reset
    configuration = ThinkingSphinx::Configuration.instance
    configuration.index_set_class = self
    configuration.render_to_file
    configuration.tenanted_index_count = pre_index_counts
    formatted_tenant = configuration.formatted_tenant(tenant)
    configuration.controller.index *indexes.collect {|i| ["#{i}_#{formatted_tenant}_core", "#{i}_#{formatted_tenant}_delta"]}.flatten
  end
end

class ThinkingSphinx::Configuration < Riddle::Configuration
  def tenanted_index_count
    @tenanted_index_count ||= {}
  end

  def tenanted_index_count=(rhs)
    @tenanted_index_count = rhs
  end

  def formatted_tenant(rhs = nil)
    (rhs || Apartment::Tenant.current).gsub('-', '_')
  end

  def index_count
    tenanted_index_count[formatted_tenant] || indices.count
  end

  def update_index_counts!
    Account.pluck(:subdomain).each {|tenant| tenanted_index_count[formatted_tenant(tenant)] ||= indices.count}
  end
end

class ThinkingSphinx::ActiveRecord::Index < Riddle::Configuration::Index
  def document_id_for_key(key)
    key * config.index_count + offset
  end
end
```

It is a bit of a mess at the moment, and it will fail if the index rake task runs without a restart, but it appears to do the job for now. I don't expect a huge volume of new tenants but it will still be nice to create one without having to restart!

**Comment by pat** [comment] 2017-01-23 06:50
Appreciate the code and thought :)

Just to make sure I'm understanding what you've done: is the index count for the document id calculations now limited to just the indices of the current tenant? And does that mean you can get identical document ids across tenant indices?

**Comment by chickenboot** [comment] 2017-01-23 07:54
It isn't limited to the current tenant, but rather all the tenants that existed before the new tenant was created. My thinking is that for a new tenant, prior to a re-index, everything is going in the delta anyway, so the document id isn't hugely important (hence the concrete requirement to restart after re-indexing, and clear out this cached index count).

A simple example would be if you had two tenants "a" and "b" that had existing data, and you added tenant "c", then after the `new_tenant_reset`, `tenanted_index_count = {'a' => 2, 'b' => 2}` – so any calls to `document_id_for_key` on `a` and `b` would be as if `c` hadn't been created at all. I'm assuming (which could be a mistake!) that it is never required for `c` because every change and new record will solely live in the delta index. Any call to `index_count` for `c` will return `3` as expected too, just in case!

**Comment by pat** [comment] 2017-01-24 07:06
So, the spanner in the works: document ids must be unique across every single index known to the daemon (not just per-index). If I'm understanding your setup correctly, User A (Database ID 1, Tenant X) and User B (Database ID 1, Tenant Y) would both end up with the same document id - is that what's happening?

**Comment by chickenboot** [comment] 2017-01-24 07:34
If we assume that tenants A-X existed before Y was created: after creation of Y, `index_count` for A-X would return 24, and for tenant Y would return 25 (and then if you create tenant Z, `tenanted_index_count` would be `{'A'..'X' => 24, 'Y' => 25, 'Z' => 26}`): i.e. for those tenants that have had a full index, the count is fixed to the index count at the time of that index, and for all new tenants, it is set at the index count post tenant creation. This way for tenants A-X the document ID returns the same one calculated at the time of the full index.  

My assumption is that because tenant Y (or Z) never uses the core index in this situation, even the potential conflict (I can't do the maths in my head, but there might be a time where `DBID * 25 + offset` overlaps with `DBID * 24 + offset`?) isn't much of a problem, but am I mistaken?

**Comment by pat** [comment] 2018-01-04 05:09
So I've left this issue open for far too long, expecting to come back and make a decision on how multi-tenancy should generally be approached. Of course, it's been almost a year and my grasp of the problem is a little fuzzier, even though the context in the comments here has certainly helped.

Some notes for those who come across this:

* I feel that TS supports multi-tenancy well enough, provided you're running a full rebuild as each tenant is added.
* If you want to run that rebuild within the context of your app, then what @chickenboot has suggested here is worth reviewing.
* If you're using per-tenant unique document IDs, rather than globally unique document ids, then yes, you could potentially get conflicts, as this is not what Sphinx expects. However, as @chickenboot has noted, given each search happens within a tenant's context, it could be fine.

Colin: Even though I'm closing this ticket, I'm still keen to hear if you're still taking this approach and whether it's continued to work well. Ditto for anyone else who finds this ticket and is using Sphinx/Thinking Sphinx in a multi-tenant setup.

**Closed by pat** 2018-01-04 05:09 UTC
