### ISSUE TITLE
Indexing issues with remote containerized sphinx

### ISSUE THREAD

**Issue by iexposure** [pat/thinking-sphinx#1088] opened 2018-03-07 19:55 UTC
Hi, Pat. I wanted to first thank you for all of the incredible work and dedication you have put into this project. It is absolutely fantastic, and we really appreciate it.

I believe we may have run into a strange error with indexing.

We initially ran sphinx and our rails app in the same container. We would run `bundle exec rake ts:rebuild` before running the web server and everything worked quite well. To improve deployments and scaling, we moved the sphinx process into its own container (identical - full rails app and db connection, just independently scalable) and pointed the rails apps to it. We had to adjust the command on the sphinx container to `bundle exec rake ts:rebuild  NODETACH=true` to work well with our environment. Everything seemed to be working, but with zero results. The log contained errors similar to those in #1036, so we updated to the newest version of sphinx (3.0.2) and thinking-sphinx (3.4.2) in an attempt to solve it. Same results - everything looked like it was working but the initial index did not populate. Callbacks would cause the item to appear in the index.

We were able to get indexing to work with no errors by adjusting the command from `bundle exec rake ts:rebuild  NODETACH=true` to `bundle exec rake ts:configure && bundle exec rake ts:start && bundle exec rake ts:rt:index && bundle exec rake ts:restart NODETACH=true`. I'm not sure if it has somethign to do with portions of `ts:rebuild` not playing nice with `NODETACH=true`, some part of `ts:rebuild` not playing liking the blank container every startup, or something entirely different. 

The workaround seems to be working very well, I just wanted to let you know our findings. It may have been part of the `WARNING: No extra index definitions found in data folder` and `WARNING: key 'docinfo' was permanently removed from Sphinx configuration. Refer to documentation for details.` warnings we were seeing in our logs.

**Comment by pat** [comment] 2018-03-11 05:30
> I'm not sure if it has somethign to do with portions of ts:rebuild not playing nice with NODETACH=true

Excellent detective work! Short of actually setting this all up myself, I'm quite sure you've figured out the cause here.

`ts:rebuild` invokes several other tasks, including `ts:start`. When NODETACH is set, then `ts:start` loads out the Sphinx daemon and holds onto that process, rather than letting it go into the background. If you're _just_ invoking `ts:start`, then that's fine… but `ts:rebuild` has stages after that point - chiefly, populating the data! - and so in this scenario those stages are never reached. This is why you're getting no search results.

I think your workaround is pretty much spot on. You could simply it to just two rake calls if you'd like: `bundle exec rake ts:rebuild && bundle exec rake ts:restart NODETACH=true`

As for the warnings - appreciate the note about them too - I'll likely deal with them in an upcoming TS version, but they certainly don't break anything for now :)

**Comment by pat** [comment] 2018-03-17 11:38
For what it's worth, the next TS (v4.0.0, which is pretty much ready to ship once Rails 5.2 is out - I want to confirm they work together before locking it all in) will have the ability to disable the docinfo setting: add `skip_docinfo: true` for each appropriate environment in `config/thinking_sphinx.yml`.

I'm going to close this issue now, given that you found a solution when logging it, and I'm quite sure of what the cause was.

**Closed by pat** 2018-03-17 11:38 UTC
