### ISSUE TITLE
Troubles with capistrano deploy

### ISSUE THREAD

**Issue by kepi** [pat/thinking-sphinx#1041] opened 2017-01-21 22:11 UTC
Hi, I'm trying to follow documentation at http://freelancing-gods.com/thinking-sphinx/deployment.html to integrate thinking sphinx into capistrano deployment.

I'm probably just overlooking something but it seams to me that only thing needed for thinking sphinx 3.3.0 should be to add this line to `Capfile`

    require 'thinking_sphinx/capistrano'

If I run deploy, nothing happens on thinking sphinx side. Also when I try to i.e. stop sphinx through cap task, nothing happens on server side again. Here is log:

```
❯ cap production thinking_sphinx:stop --trace
** Invoke production (first_time)
** Execute production
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke rbenv:validate (first_time)
** Execute rbenv:validate
 DEBUG [7782e15d] Running [ -d /opt/rbenv/versions/1.9.3 ] as user@some.server
 DEBUG [7782e15d] Command: [ -d /opt/rbenv/versions/1.9.3 ]
 DEBUG [7782e15d] Finished in 0.294 seconds with exit status 0 (successful).
** Invoke rbenv:map_bins (first_time)
** Invoke passenger:rbenv:hook (first_time)
** Invoke passenger:test_which_passenger (first_time)
** Execute passenger:test_which_passenger
 DEBUG [a1ec3c0f] Running /usr/bin/env which passenger as user@some.server
 DEBUG [a1ec3c0f] Command: /usr/bin/env which passenger
 DEBUG [a1ec3c0f]       /usr/bin/passenger
 DEBUG [a1ec3c0f] Finished in 0.042 seconds with exit status 0 (successful).
** Execute passenger:rbenv:hook
** Execute rbenv:map_bins
** Invoke bundler:map_bins (first_time)
** Invoke passenger:bundler:hook (first_time)
** Execute passenger:bundler:hook
** Execute bundler:map_bins
** Invoke thinking_sphinx:stop (first_time)
** Execute thinking_sphinx:stop
```

It looks like thinking_sphinx:stop is executing but sphinx is still present with same PID on server. I checked if I have PID file correctly set and that there is correct value in it. When using `bundle exec rake ts:stop` on server, it works as it should.

I'm using Capistrano 3.4.1 with rbenv, bundler and passenger.

Thanks for any hint.

**Comment by pat** [comment] 2017-01-22 07:54
Hi @kepi,

You're right that there's only one `require` statement needed - the docs cover a few different options depending on the version of Thinking Sphinx people are using (the comments preceding each require statement mention this).

As for deploys - there is no automatic invoking of Thinking Sphinx-related tasks during the standard capistrano workflow. Certainly, you're welcome to add hooks around that as you wish.

The fact that stop isn't working, though, certainly sounds like unexpected behaviour! Do you have the paths set up for your production environment as noted in the Basics section of the deployment docs so you're using shared paths rather than release-specific paths?

**Comment by kepi** [comment] 2017-01-22 16:45
Thanks for quick answer @pat 

It would be great to add mention about automatic invoking and maybe even example how to do it with every deploy. Or maybe only when thinking_sphinx config changes if that is even possible.

Yes, I'm using shared paths, here is my ts config:

```
master: &master
  enable_star: true
  min_infix_len: 1
  morphology: stem_cz

production:
  <<: *master
  mysql41: 9421
  address: 127.0.0.1
  pid_file: /data/app/shared/tmp/searchd.pid
  indices_location: /data/app/shared/db/sphinx
  configuration_file: /data/app/shared/config/production.sphinx.conf
  binlog_path: /data/app/shared/binlog
```

**Comment by pat** [comment] 2017-01-23 06:14
Hmm, your configuration looks fine to me. I'm wondering if it's worth writing a custom Capistrano task to invoke `rake ts:stop --trace`? What I'm particularly keen to see is the output from the rake call, which should hopefully provide some clues as to why it's not working.

Regarding the automatic invoking - to be honest, my Capistrano knowledge is pretty rusty, so I'm really not sure if there is a good way to allow automatic invocation of TS tasks, nor if there are clear situations for certain tasks to definitely be invoked. I'm open to discussing such things, but I think that could be a separate issue (and even, possibly, a separate gem!).

**Comment by JasonBarnabe** [comment] 2017-01-29 21:53
I have been having trouble with Sphinx as well since switching to Capistrano deployment. Any updated content disappears from the results. I'm not sure what makes the problem start occurring at the moment. Here's some of my interactions with it, starting from a state where the problem is occurring.

```
[www@greasyfork current]$ ps aux | grep searchd
www       4870  0.0  0.0  32816  1248 ?        S    21:41   0:00 searchd --pidfile --config /home/www/greasyfork/shared/config/production.sphinx.conf
www       4871  0.1  0.0 112984 10104 ?        Sl   21:41   0:00 searchd --pidfile --config /home/www/greasyfork/shared/config/production.sphinx.conf
www       5252  0.0  0.0 103308   876 pts/1    R+   21:42   0:00 grep searchd
[www@greasyfork current]$ RAILS_ENV=production rake ts:stop
rake aborted!
Riddle::CommandFailedError: Sphinx command failed to execute
/home/www/greasyfork/shared/bundle/ruby/2.3.0/gems/riddle-2.0.0/lib/riddle/execute_command.rb:23:in `call'
/home/www/greasyfork/shared/bundle/ruby/2.3.0/gems/riddle-2.0.0/lib/riddle/execute_command.rb:5:in `call'
/home/www/greasyfork/shared/bundle/ruby/2.3.0/gems/riddle-2.0.0/lib/riddle/controller.rb:53:in `stop'
/home/www/greasyfork/shared/bundle/ruby/2.3.0/gems/thinking-sphinx-3.2.0/lib/thinking_sphinx/rake_interface.rb:84:in `stop'
/home/www/greasyfork/shared/bundle/ruby/2.3.0/gems/thinking-sphinx-3.2.0/lib/thinking_sphinx/tasks.rb:49:in `block (2 levels) in <top (required)>'
/home/www/greasyfork/shared/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/www/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/home/www/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => ts:stop
(See full trace by running task with --trace)
[www@greasyfork current]$ RAILS_ENV=production rake ts:stop --verbose
searchd is not currently running.
Stopped searchd daemon (pid: 12417).
[www@greasyfork current]$ ps aux | grep searchd
www       4795  0.0  0.0 103308   860 pts/1    S+   21:40   0:00 grep searchd
[www@greasyfork current]$ RAILS_ENV=production rake ts:start --verbose
Started searchd successfully (pid: 4871).
[www@greasyfork current]$ ps aux | grep searchd
www       4870  0.0  0.0  32816  1248 ?        S    21:41   0:00 searchd --pidfile --config /home/www/greasyfork/shared/config/production.sphinx.conf
www       4871  0.4  0.0 112984 10048 ?        Sl   21:41   0:00 searchd --pidfile --config /home/www/greasyfork/shared/config/production.sphinx.conf
www       4881  0.0  0.0 103308   864 pts/1    S+   21:41   0:00 grep searchd
[www@greasyfork config]$ cat /home/www/greasyfork/shared/log/production.sphinx.pid
4871
```

Not sure if this helpful. If you have any suggestion on things to check the next time it occurs, I will post here.

**Comment by pat** [comment] 2017-01-30 00:14
Hi Jason,

Can you try upgrading to TS v3.3.0? There's been some changes in Riddle related to stopping/starting the daemon, and the latest TS release is better placed to offer useful feedback, which may help debugging things further.

Also, looks like your configuration file and pid file are in the shared folder, which is great. Are the index files also there?

**Comment by JasonBarnabe** [comment] 2017-01-30 03:59
`current/db/sphinx` is a symlink to `shared/db/sphinx`. In `production.sphinx.conf`, I see `path = /home/www/greasyfork/releases/20170129213629/db/sphinx/production/script_core`.

**Comment by pat** [comment] 2017-01-30 04:01
I would recommend changing it to just use the actual shared path rather than relying on a symlink. Otherwise, unless you reconfigure after every deploy, you could end up with old/invalid paths in the configuration file. Also, using shared path everywhere is more consistent :)

**Comment by JasonBarnabe** [comment] 2017-01-30 04:07
I will try that and also upgrade to 3.3.0.

It would be good in http://freelancing-gods.com/thinking-sphinx/deployment.html to explicitly say that symlinking in the files or folders doesn't work. Because my files are indeed already in the `shared` folder, and I thought that this was enough.

**Comment by pat** [comment] 2017-01-30 11:30
Good suggestion - I've just added a note to the docs about symlinked directories.

**Comment by pat** [comment] 2017-04-21 12:54
It's been a few months since this issue was last referenced, so I'm going to close it. Feel free to discuss the issue further, though - and if we need to, I can always re-open it.

**Closed by pat** 2017-04-21 12:54 UTC
