### ISSUE TITLE
Upgrading to Sphinx 3.1.1 No local indexes found

### ISSUE THREAD

**Issue by bkd** [pat/thinking-sphinx#1148] opened 2019-10-11 14:08 UTC
I just updated to Sphinx 3.1.1 and latest version of Thinking Sphinx

I've deleted all the indexes from the old 2.2.11 version, then did rake ts:configure, rebuild 
I get a bag of errors

WARNING: attribute 'sphinx_internal_id' not found - IGNORING
WARNING: attribute 'sphinx_deleted' not found - IGNORING
WARNING: attribute 'created_at' not found - IGNORING
WARNING: attribute 'updated_at' not found - IGNORING
WARNING: attribute 'sphinx_internal_class' not found - IGNORING
WARNING: attribute 'interview_stage' not found - IGNORING
WARNING: attribute 'interview_interviewers_name' not found - IGNORING
WARNING: attribute 'interview_person_name' not found - IGNORING
WARNING: attribute 'interview_assignment_name' not found - IGNORING
WARNING: attribute 'interview_company_name' not found - IGNORING
ERROR: index 'interview': no full text fields in schema, nothing to index!.

Alongside this once its up and running I get 

ThinkingSphinx::SphinxError (no enabled local indexes to search ...

I have lots more errors

Sphinx 3.1.1 (commit 612d99f)
Copyright (c) 2001-2018, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file 'config/production.sphinx.conf'...
WARNING: key 'max_matches' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'docinfo' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'charset_type' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'docinfo' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'charset_type' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: 196 more warnings skipped.

And of course nothing seems to work at all. 

The indexing seems waaaay faster than the v2 of Sphinx, so I am have no real idea if this is working. 

Anyone else found this issue or have an idea what to do?

**Comment by pat** [comment] 2019-10-14 02:20
That's definitely not the expected output… 🤔

Are you able to try it again after deleting the binlog files as well? (If you haven't tried that already) And is it possible for you to share an index definition from your app, and the generated Sphinx configuration file as well? (Make sure to remove any sensitive information from that - in particular, database passwords).

**Comment by bkd** [comment] 2019-10-15 12:25
Yes deleted the binlog files, 
I've got a huge config file using multiple tenants, so copied just a single table definition the rest is exactly the same 

```

Apartment::Tenant.each do |tenant|
  ThinkingSphinx::Index.define :interview, with: :active_record, delta: ThinkingSphinx::Deltas::SidekiqDelta, name: "interview_#{tenant}" do
    indexes id, as: :interview_id
    set_property :sql_query_pre => ["set schema '#{tenant}';"]
    indexes subject, as: :interview_subject
    indexes result, as: :interview_result
    indexes location, as: :interview_address
    indexes stage, as: :interview_stage, sortable: true
    indexes interviewers.person.name, as: :interview_interviewers_name, sortable: true
    indexes person.name, as: :interview_person_name, sortable: true
    indexes assignment.name, as: :interview_assignment_name, sortable: true
    indexes company.name, as: :interview_company_name, sortable: true
    has created_at, updated_at
  end
  ....
end
```
production config

```
indexer
{
  mem_limit = 2048M
  write_buffer = 2M
}

searchd
{
  listen = 127.0.0.1:9306:mysql41
  log = /web/deployed/log/production.searchd.log
  query_log = /web/deployed/log/production.searchd.query.log
  pid_file = /web/deployed/log/production.sphinx.pid
  max_matches = 1000
  workers = threads
  binlog_path = /web/deployed/tmp/binlog/production
}

source interview_eximia_core_0
{
  type = pgsql
  sql_host = localhost
  sql_user = rails
  sql_pass = xxxxxxxx
  sql_db = xxxxxxxx_production
  sql_query_pre = set schema 'eximia';
  sql_query_pre = SET TIME ZONE UTC
  sql_query_pre = UPDATE "interviews" SET "delta" = FALSE WHERE "delta" = TRUE
  sql_query = SELECT "interviews"."id" * 113 + 0 AS "id", "interviews"."id" AS "interview_id", "interviews"."subject" AS "interview_subject", "interviews"."result" AS "interview_result", "interviews"."location" AS "interview_address", "interviews"."stage" AS "interview_stage", array_to_string(array_agg(DISTINCT "people"."name"), ' ') AS "interview_interviewers_name", "people_interviews"."name" AS "interview_person_name", "assignments"."name" AS "interview_assignment_name", "companies"."name" AS "interview_company_name", "interviews"."id" AS "sphinx_internal_id", 'Interview' AS "sphinx_internal_class", 0 AS "sphinx_deleted", extract(epoch from "interviews"."created_at")::int AS "created_at", extract(epoch from "interviews"."updated_at")::int AS "updated_at" FROM "interviews" LEFT OUTER JOIN "interviewers" ON "interviewers"."interview_id" = "interviews"."id" LEFT OUTER JOIN "people" ON "people"."id" = "interviewers"."person_id" LEFT OUTER JOIN "people" "people_interviews" ON "people_interviews"."id" = "interviews"."person_id" LEFT OUTER JOIN "assignments" ON "assignments"."id" = "interviews"."assignment_id" LEFT OUTER JOIN "companies" ON "companies"."id" = "interviews"."company_id" WHERE ("interviews"."id" BETWEEN $start AND $end) GROUP BY "interviews"."id", "interviews"."id", "interviews"."subject", "interviews"."result", "interviews"."location", "interviews"."stage", "people_interviews"."name", "assignments"."name", "companies"."name", "interviews"."id", "interviews"."created_at", "interviews"."updated_at"
  sql_query_range = SELECT COALESCE(MIN("interviews"."id"), 1), COALESCE(MAX("interviews"."id"), 1) FROM "interviews"
  sql_attr_uint = sphinx_internal_id
  sql_attr_uint = sphinx_deleted
  sql_attr_timestamp = created_at
  sql_attr_timestamp = updated_at
  sql_attr_string = sphinx_internal_class
  sql_field_string = interview_stage
  sql_field_string = interview_interviewers_name
  sql_field_string = interview_person_name
  sql_field_string = interview_assignment_name
  sql_field_string = interview_company_name
}

index interview_eximia_core
{
  type = plain
  path = /web/deployed/db/sphinx/production/interview_eximia_core
  docinfo = extern
  min_stemming_len = 2
  exceptions = /web/deployed/db/exceptions.txt
  min_word_len = 2
  charset_type = sbcs
  charset_table = 0..9, A..Z->a..z, _, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F, U+0023, U+23
  min_prefix_len = 2
  source = interview_eximia_core_0
}

source interview_eximia_delta_0
{
  type = pgsql
  sql_host = localhost
  sql_user = rails
  sql_pass = xxxxxxxx
  sql_db = xxxxxxxx_production
  sql_query_pre = set schema 'eximia';
  sql_query_pre = SET TIME ZONE UTC
  sql_query = SELECT "interviews"."id" * 113 + 0 AS "id", "interviews"."id" AS "interview_id", "interviews"."subject" AS "interview_subject", "interviews"."result" AS "interview_result", "interviews"."location" AS "interview_address", "interviews"."stage" AS "interview_stage", array_to_string(array_agg(DISTINCT "people"."name"), ' ') AS "interview_interviewers_name", "people_interviews"."name" AS "interview_person_name", "assignments"."name" AS "interview_assignment_name", "companies"."name" AS "interview_company_name", "interviews"."id" AS "sphinx_internal_id", 'Interview' AS "sphinx_internal_class", 0 AS "sphinx_deleted", extract(epoch from "interviews"."created_at")::int AS "created_at", extract(epoch from "interviews"."updated_at")::int AS "updated_at" FROM "interviews" LEFT OUTER JOIN "interviewers" ON "interviewers"."interview_id" = "interviews"."id" LEFT OUTER JOIN "people" ON "people"."id" = "interviewers"."person_id" LEFT OUTER JOIN "people" "people_interviews" ON "people_interviews"."id" = "interviews"."person_id" LEFT OUTER JOIN "assignments" ON "assignments"."id" = "interviews"."assignment_id" LEFT OUTER JOIN "companies" ON "companies"."id" = "interviews"."company_id" WHERE ("interviews"."delta" = TRUE AND "interviews"."id" BETWEEN $start AND $end) GROUP BY "interviews"."id", "interviews"."id", "interviews"."subject", "interviews"."result", "interviews"."location", "interviews"."stage", "people_interviews"."name", "assignments"."name", "companies"."name", "interviews"."id", "interviews"."created_at", "interviews"."updated_at"
  sql_query_range = SELECT COALESCE(MIN("interviews"."id"), 1), COALESCE(MAX("interviews"."id"), 1) FROM "interviews" WHERE ("interviews"."delta" = TRUE)
  sql_attr_uint = sphinx_internal_id
  sql_attr_uint = sphinx_deleted
  sql_attr_timestamp = created_at
  sql_attr_timestamp = updated_at
  sql_attr_string = sphinx_internal_class
  sql_field_string = interview_stage
  sql_field_string = interview_interviewers_name
  sql_field_string = interview_person_name
  sql_field_string = interview_assignment_name
  sql_field_string = interview_company_name
}

index interview_eximia_delta
{
  type = plain
  path = /web/deployed/db/sphinx/production/interview_eximia_delta
  docinfo = extern
  min_stemming_len = 2
  exceptions = /web/deployed/db/exceptions.txt
  min_word_len = 2
  charset_type = sbcs
  charset_table = 0..9, A..Z->a..z, _, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F, U+0023, U+23
  min_prefix_len = 2
  blend_chars = U+20, @, ., #, +
  source = interview_eximia_delta_0
}

...
```

**Comment by pat** [comment] 2019-10-15 12:50
I doubt it's the cause, but one thing I've spotted is the `charset_type` setting - I'm pretty certain this has been removed, so try removing that from your `config/thinking_sphinx.yml` file and see if it makes any difference?

**Comment by pat** [comment] 2019-10-15 12:53
And going by the warnings, you may also want to remove max_matches if you're setting that as well. Plus, you can add `skip_docinfo: true` per environment in `config/thinking_sphinx.yml` to remove that setting being generated as well. Hopefully that brings down the number of warnings?

**Comment by bkd** [comment] 2019-10-15 18:01
added skip_docinfo: true,  removed charset_type and max_matches, re-indexed and the indexing seemed to run slightly faster than the v2, but similar to what I expected. Seems to have done the trick.

**Comment by bkd** [comment] 2019-10-15 18:33
Setting this made it work, alongwith the other settings above;

>   mem_limit: 1096M

**Comment by bkd** [comment] 2019-10-15 18:44
Now i have a further error where Sphinx blows up, its gets stuck half way through with

> ERROR: index 'person_eximia_core': sql_fetch_row: .

Tracing this led to nothing, --dump-rows-sql didnt give anything either!

**Comment by pat** [comment] 2019-10-16 10:55
You could be across this already, but: Thinking Sphinx configures Sphinx to query for records in a paginated fashion (see the `$start` and `$end` placeholders in `sql_query`, and the overall max/min values are gathered by `sql_query_range`). The default window jumps the start/end ranges by 1024 each time (though this can be customised with the `sql_range_step` setting).

Going by [this forum post](http://sphinxsearch.com/forum/view.html?id=16081) it seems the error you're facing is when one of those windows has no records (say, Sphinx has requested the second page, with ids between 1025-2048, but none of those rows exist, or are being filtered out by the WHERE clause in other ways). It's not the first time I've heard of someone hitting this bug, and it's an annoying one 😒

Your options are either to set `sql_range_step` to be a larger number (which can be done in `config/thinking_sphinx.yml`), or you can use `set_property :disable_range? => true` in your index definition to avoid the paginated indexing. Given you've already had to bump up the `mem_limit` value, though, this second suggestion doesn't sound ideal, because it'll lead to all records for a given index being returned by your database in a single request, and Sphinx then processing them all.

**Comment by bkd** [comment] 2019-10-17 03:21
Thanks for the explanation, its a bit annoying but now I can solve in future if this happens again.

sphinx_internal_id has been removed in the latest version 3.1.1 is that also a concern for anything?

**Comment by bkd** [comment] 2019-10-17 10:06
Also can I check Sphinx3.1.1 doesnt index an empty result set so when  ThinkingSphinx::Deltas::SidekiqDelta::FlagAsDeletedJob runs it hits an error on the Sidekiq logs 

> ThinkingSphinx::SphinxError: index interview_eximia_core: index not available - UPDATE email_eximia_core SET sphinx_deleted = 1 WHERE id = 3283340

At indexing time I get the following

> ERROR: index 'interview_eximia_delta': no full text fields in schema, nothing to index!.

**Comment by pat** [comment] 2019-10-17 11:42
`sphinx_internal_id` is generated by Thinking Sphinx - it's not a generic Sphinx thing - and it should still be there in each source!

That second error you've noted is rather odd - I'm presuming you have at least one field in each index. Can you confirm that's the case in the generated Sphinx file? Granted, the first error suggests the indices for that tenant weren't processed successfully 🤔

**Comment by bkd** [comment] 2019-10-17 13:06
It seems that Sphinx wont create any delta indexes at all unless there is 1 record in the table with delta set to true. I updated 1 record per table with delta set to true then rerun the indexer per index and it solved the problem. If I ts:rebuild after ts:merge, I will need to do the same again. Running ts:merge after the delta indexes are created should be fine.

**Comment by pat** [comment] 2019-10-18 02:51
Ah… right. I'm now thinking that Sphinx v3.1.1 just isn't worth upgrading to, at least when using SQL-backed indices. The fact it can't handle empty indices is a pretty big issue, especially with deltas.

Maybe v2.3.2 is worth trying? Or Manticore as a drop-in replacement for Sphinx may be worth investigating.

**Comment by bkd** [comment] 2019-10-25 09:49
So after racking my brain and now getting loads of errors on missing indices, I found that the dumprows output would fail on the CREATE table SQL. 

```
DROP TABLE IF EXISTS rows_email_eximia_delta_0;

CREATE TABLE rows_email_eximia_delta_0 (
  id VARCHAR(32) NOT NULL,
  email_id VARCHAR(4096) NOT NULL,
  email_subject VARCHAR(4096) NOT NULL,
  email_to_address VARCHAR(4096) NOT NULL,
  email_body VARCHAR(4096) NOT NULL,
  email_sender_name VARCHAR(4096) NOT NULL,
  email_person_name VARCHAR(4096) NOT NULL,
  sphinx_internal_id VARCHAR(4096) NOT NULL,
  sphinx_internal_class VARCHAR(4096) NOT NULL,
  sphinx_deleted VARCHAR(4096) NOT NULL,
  created_at VARCHAR(4096) NOT NULL,
  updated_at VARCHAR(4096) NOT NULL,
  KEY(id) );
```
with the config

```
source email_eximia_delta_0
{
  type = pgsql
  sql_host = localhost
  sql_user = xxxx
  sql_pass = xxx
  sql_db = xxxx
  sql_query_pre = set schema 'eximia';
  sql_query_pre = SET TIME ZONE UTC
  sql_query = SELECT "emails"."id" * 38 + 12 AS "id", "emails"."id" AS "email_id", "emails"."subject" AS "email_subject", "emails"."to_address" AS "email_to_address", "emails"."body" AS "email_body", "emails"."sender_name" AS "email_sender_name", "people"."name" AS "email_person_name", "emails"."id" AS "sphinx_internal_id", 'Email' AS "sphinx_internal_class", 0 AS "sphinx_deleted", extract(epoch from "emails"."created_at")::int AS "created_at", extract(epoch from "emails"."updated_at")::int AS "updated_at" FROM "emails" LEFT OUTER JOIN "email_relations" ON "email_relations"."email_id" = "emails"."id" LEFT OUTER JOIN "people" ON "people"."id" = "email_relations"."person_id" WHERE ("emails"."delta" = TRUE AND "emails"."id" BETWEEN $start AND $end) GROUP BY "emails"."id", "emails"."id", "emails"."subject", "emails"."to_address", "emails"."body", "emails"."sender_name", "people"."name", "emails"."id", "emails"."created_at", "emails"."updated_at"
  sql_query_range = SELECT COALESCE(MIN("emails"."id"), 1), COALESCE(MAX("emails"."id"), 1) FROM "emails" WHERE ("emails"."delta" = TRUE)
  sql_attr_uint = sphinx_internal_id
  sql_attr_uint = sphinx_deleted
  sql_attr_timestamp = created_at
  sql_attr_timestamp = updated_at
  sql_attr_string = sphinx_internal_class
}

index email_eximia_delta
{
  type = plain
  path = /web/deployed/db/sphinx/production/email_eximia_delta
  min_stemming_len = 2
  exceptions = /web/deployed/db/exceptions.txt
  min_word_len = 2
  charset_table = 0..9, A..Z->a..z, _, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F, U+0023, U+23
  min_prefix_len = 2
  source = email_eximia_delta_0
}
```

This fails on the indexer command 

`indexer --dump-rows-sql dumprows.txt --config config/production.sphinx.conf --rotate email_eximia_delta
`
I ran the create table SQL that was in the dumprows.txt output and get 


> ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "("
> LINE 14:   KEY(id) )

**Comment by bkd** [comment] 2019-10-25 10:07
Looking into manticore - looks good, in the meantime I have downgraded to 2.3.2.

**Comment by pat** [comment] 2019-10-28 12:28
I wonder if the `CREATE TABLE` statement is MySQL-specific? 🤔  But good to know you've switched to v2.3.2, definitely sounds like that's the wise option for now.

**Comment by pat** [comment] 2020-01-20 11:53
This issue's been dormant for a couple of months, so I'm going to close it - though further comments are welcome! - but it sounds like Sphinx v3.1.1 is not worthwhile if any empty indices are in play (and if you're using deltas, then that means you really shouldn't use Sphinx v3.1.1). Alternatives are v2.2.11 or v2.3.2, or switching to Manticore (which is a drop-in replacement for Sphinx, and works with Thinking Sphinx).

**Closed by pat** 2020-01-20 11:53 UTC
