### ISSUE TITLE
ThinkingSphinx::ConnectionError: Error connecting to Sphinx via the MySQL protocol. Can't connect to MySQL server on '127.0.0.1' (115)

### ISSUE THREAD

**Issue by vol1ura** [pat/thinking-sphinx#1225] opened 2022-06-08 14:27 UTC
Hello @pat . I have this error in my development environment in docker container. My config is
```yaml
development: &dev
  utf8: true
  indices_location: db/sphinx/development
  mysql41: 9406
```
When I run `rake ts:configure ts:restart`
```bash
Generating configuration to /usr/src/config/development.sphinx.conf
Sphinx 3.1.1 (commit 612d99f)
Copyright (c) 2001-2018, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/usr/src/config/development.sphinx.conf'...
stop: successfully sent SIGTERM to pid 26

The Sphinx stop command failed:
  Command: searchd --pidfile --config "/usr/src/config/development.sphinx.conf" --stopwait
  Status:  1
  Output:  See above

There may be more information about the failure in /usr/src/log/development.searchd.log.
```
and no records in `/usr/src/log/development.searchd.log`. And after command `rake ts:rebuild` I have the same output whith stopping container (Error 137).

This is Rails 6.1 app with mariadb:10.5.12

Can't find same errors, hope you can help with it.

**Comment by vol1ura** [comment] 2022-06-08 17:43
This error constantly occurs when using `puma`. When I replace the `puma` with a `thin`, it occurs  rarely.

**Comment by pat** [comment] 2022-06-11 02:34
Hi @vol1ura - this is an odd error indeed! I'm really not sure what the cause is - the output suggests Sphinx has stopped successfully, so the fact that the command returns a status of 1 (instead of 0) is surprising.

Also, the fact that it's different between using `thin` and `puma` is confusing too. I'm not sure if it's related, but maybe it's worth trying a different Sphinx version (v2.2.11 or v3.4.1), or even a Manticore release instead of Sphinx?

**Comment by pat** [comment] 2022-12-30 02:16
Hi @vol1ura - I'm going to close this issue as it's been a few months without any change here. That said: if you find it's still a problem and have any further questions/fixes, please do comment, I'll be happy to re-open the issue.

**Closed by pat** 2022-12-30 02:16 UTC
