### ISSUE TITLE
How can I intercept the error with connect to local MySQL server?

### ISSUE THREAD

**Issue by xxx44yyy** [pat/thinking-sphinx#1104] opened 2018-07-14 00:06 UTC
Sometimes the connection to mysql is lost. I don't know why. I see an error: 

> Can't connect to local MySQL server through socket

At this point, the site can not be used (my clients get angry and swear). I want to somehow catch the error and restart Sphinx and MySQL. How best to do this?

**Comment by pat** [comment] 2018-07-14 00:57
Does this error happen every time? Also, which versions of Sphinx, MySQL and Thinking Sphinx are you using?

**Comment by xxx44yyy** [comment] 2018-07-14 01:18
> Does this error happen every time? 
Sometimes once every few days. Sometimes more. I didn't notice any exact periodicity.


> Also, which versions of Sphinx, MySQL and Thinking Sphinx are you using?
Sphinx: 3.0.3
Mysql: I don't have access to the server now, so I don't know the MySQL version.
Thinking Sphinx: 4.0

I got a call from a customer describing a problem. A few hours later he said that the site was already working. This means that the connection was first lost, and then appeared. 

I looked at the cron and saw there the periodic re-indexation. It is possible that reindexing somehow restarted sphinx. Or Thinking Sphinx.

**Comment by xxx44yyy** [comment] 2018-07-14 01:38
In the cron, this code is starting every 5 minutes:
`configuration = ThinkingSphinx::Configuration.instance
configuration.preload_indices

delta_index_names = configuration.indices.select(&:delta?).collect(&:name)
configuration.controller.index *delta_index_names`

Every midnight:
`rake ts:index`

Every reboot:
`rake ts:start`


> Hmm, those versions are probably okay. There's a bug between Sphinx and MySQL 8, but that means no search queries work, and the fact that this is generally fine for you suggests that's not the problem.
> Also, Thinking Sphinx retries search queries three times by default - so, the fact that you're seeing this error suggests that Sphinx has actually been stopped at the time (i.e. it's persisting for more than a few milliseconds).

Maybe it's a collision? I now can not understand what is happening, so I'm thinking about how you can catch a mistake. Or how to reproduce it. Strange behavior of the system.

**Comment by pat** [comment] 2018-07-14 01:39
Hmm, I'm not sure what the cause is yet. Is there a stack-trace for the error?

**Comment by xxx44yyy** [comment] 2018-07-14 01:41
I don't have access to the server, but wait 5 minutes, I'll ask someone to help.

**Comment by xxx44yyy** [comment] 2018-07-14 01:50
```
E, [2018-07-10T16:17:09.828275 #7025] ERROR -- : Can't connect to local MySQL server through socket '/var/tmp/prod.sphinx' (111)
E, [2018-07-10T16:17:09.828300 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `connect'
E, [2018-07-10T16:17:09.828318 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `initialize'
E, [2018-07-10T16:17:09.828336 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/connection/mri.rb:13:in `new'
E, [2018-07-10T16:17:09.828352 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/connection/mri.rb:13:in `client'
E, [2018-07-10T16:17:09.828369 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/connection/client.rb:28:in `close!'
E, [2018-07-10T16:17:09.828385 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/connection.rb:28:in `block in pool'
E, [2018-07-10T16:17:09.828403 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/innertube-1.1.0/lib/innertube.rb:88:in `delete_element'
E, [2018-07-10T16:17:09.828420 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/innertube-1.1.0/lib/innertube.rb:140:in `rescue in take'
E, [2018-07-10T16:17:09.828437 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/innertube-1.1.0/lib/innertube.rb:148:in `take'
E, [2018-07-10T16:17:09.828453 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/connection.rb:36:in `take'
E, [2018-07-10T16:17:09.828470 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/deltas/delete_job.rb:12:in `block in perform'
E, [2018-07-10T16:17:09.828489 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
E, [2018-07-10T16:17:09.828506 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
E, [2018-07-10T16:17:09.828524 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
E, [2018-07-10T16:17:09.828542 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/logger.rb:5:in `log'
E, [2018-07-10T16:17:09.828560 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/deltas/delete_job.rb:11:in `perform'
E, [2018-07-10T16:17:09.828579 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/deltas/default_delta.rb:19:in `delete'
E, [2018-07-10T16:17:09.828596 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/active_record/callbacks/delta_callbacks.rb:16:in `block in after_commit'
E, [2018-07-10T16:17:09.828614 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/active_record/callbacks/delta_callbacks.rb:15:in `each'
E, [2018-07-10T16:17:09.828630 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/active_record/callbacks/delta_callbacks.rb:15:in `after_commit'
E, [2018-07-10T16:17:09.828646 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/thinking-sphinx-4.0.0/lib/thinking_sphinx/callbacks.rb:9:in `block (2 levels) in callbacks'
E, [2018-07-10T16:17:09.828662 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:413:in `block in make_lambda'
E, [2018-07-10T16:17:09.828678 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:270:in `block in simple'
E, [2018-07-10T16:17:09.828694 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:511:in `block in invoke_after'
E, [2018-07-10T16:17:09.828710 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:511:in `each'
E, [2018-07-10T16:17:09.828725 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:511:in `invoke_after'
E, [2018-07-10T16:17:09.828741 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:132:in `run_callbacks'
E, [2018-07-10T16:17:09.828756 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:827:in `_run_commit_callbacks'
E, [2018-07-10T16:17:09.828771 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-5.1.6/lib/active_record/transactions.rb:343:in `committed!'
E, [2018-07-10T16:17:09.828787 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:86:in `commit_records'
E, [2018-07-10T16:17:09.828864 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:178:in `block in commit_transaction'
E, [2018-07-10T16:17:09.828882 #7025] ERROR -- : /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
E, [2018-07-10T16:17:09.828898 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:168:in `commit_transaction'
E, [2018-07-10T16:17:09.828914 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:207:in `block in within_new_transaction'
E, [2018-07-10T16:17:09.828931 #7025] ERROR -- : /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
E, [2018-07-10T16:17:09.828947 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
E, [2018-07-10T16:17:09.828963 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-5.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:235:in `transaction'
E, [2018-07-10T16:17:09.828979 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-5.1.6/lib/active_record/transactions.rb:210:in `transaction'
E, [2018-07-10T16:17:09.828996 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-5.1.6/lib/active_record/transactions.rb:381:in `with_transaction_returning_status'
E, [2018-07-10T16:17:09.829012 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-5.1.6/lib/active_record/transactions.rb:308:in `block in save'
E, [2018-07-10T16:17:09.829027 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-5.1.6/lib/active_record/transactions.rb:323:in `rollback_active_record_state!'
E, [2018-07-10T16:17:09.829043 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-5.1.6/lib/active_record/transactions.rb:307:in `save'
E, [2018-07-10T16:17:09.829059 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-5.1.6/lib/active_record/suppressor.rb:42:in `save'
E, [2018-07-10T16:17:09.829074 #7025] ERROR -- : /web/tmp_project/lib/customers/handlers/paper_info.rb:25:in `block (2 levels) in perform'
E, [2018-07-10T16:17:09.829090 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/rubyzip-1.2.1/lib/zip/entry_set.rb:38:in `block in each'
E, [2018-07-10T16:17:09.829105 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/rubyzip-1.2.1/lib/zip/entry_set.rb:37:in `each'
E, [2018-07-10T16:17:09.829122 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/rubyzip-1.2.1/lib/zip/entry_set.rb:37:in `each'
E, [2018-07-10T16:17:09.829178 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/rubyzip-1.2.1/lib/zip/central_directory.rb:182:in `each'
E, [2018-07-10T16:17:09.829195 #7025] ERROR -- : /web/tmp_project/lib/customers/handlers/paper_info.rb:5:in `block in perform'
E, [2018-07-10T16:17:09.829211 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/rubyzip-1.2.1/lib/zip/file.rb:101:in `open'
E, [2018-07-10T16:17:09.829226 #7025] ERROR -- : /web/tmp_project/lib/file/handlers/paper_info.rb:4:in `perform'
E, [2018-07-10T16:17:09.829243 #7025] ERROR -- : /web/tmp_project/lib/building_worker.rb:195:in `work'
E, [2018-07-10T16:17:09.829258 #7025] ERROR -- : /web/tmp_project/lib/building_worker.rb:130:in `block in worker'
E, [2018-07-10T16:17:09.829274 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-5.1.6/lib/active_record/relation/delegation.rb:39:in `each'
E, [2018-07-10T16:17:09.829289 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-5.1.6/lib/active_record/relation/delegation.rb:39:in `each'
E, [2018-07-10T16:17:09.829304 #7025] ERROR -- : /web/tmp_project/lib/building_worker.rb:127:in `worker'
E, [2018-07-10T16:17:09.829319 #7025] ERROR -- : /web/tmp_project/lib/building_worker.rb:29:in `perform'
E, [2018-07-10T16:17:09.829334 #7025] ERROR -- : /web/tmp_project/lib/tasks/building_worker.rake:8:in `block in <top (required)>'
E, [2018-07-10T16:17:09.829349 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
E, [2018-07-10T16:17:09.829364 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
E, [2018-07-10T16:17:09.829379 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
E, [2018-07-10T16:17:09.829396 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
E, [2018-07-10T16:17:09.829411 #7025] ERROR -- : /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
E, [2018-07-10T16:17:09.829426 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
E, [2018-07-10T16:17:09.829506 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
E, [2018-07-10T16:17:09.829523 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
E, [2018-07-10T16:17:09.829539 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
E, [2018-07-10T16:17:09.829554 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
E, [2018-07-10T16:17:09.829570 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
E, [2018-07-10T16:17:09.829586 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
E, [2018-07-10T16:17:09.829601 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
E, [2018-07-10T16:17:09.829617 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
E, [2018-07-10T16:17:09.829632 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
E, [2018-07-10T16:17:09.829648 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
E, [2018-07-10T16:17:09.829664 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
E, [2018-07-10T16:17:09.829681 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/bin/rake:23:in `load'
E, [2018-07-10T16:17:09.829696 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/bin/rake:23:in `<main>'
E, [2018-07-10T16:17:09.829711 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
E, [2018-07-10T16:17:09.829726 #7025] ERROR -- : /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by xxx44yyy** [comment] 2018-07-14 19:53
Think about it?

**Comment by pat** [comment] 2018-07-14 23:17
I'm still not sure what the problem is, but some thoughts that may help debugging:

* Does the Sphinx log have anything in it around the same time as these errors are occurring?
* Do the errors happen at the same time of day? Is there any pattern at all to the error times?
* You've got Sphinx set up to use a UNIX socket rather than a TCP port - which should be fine! - but this is a new feature for Thinking Sphinx, so I'm not as experienced with debugging it. Perhaps it's worth trying TCP ports instead and see if that is more reliable?

**Comment by xxx44yyy** [comment] 2018-07-14 23:39
> Does the Sphinx log have anything in it around the same time as these errors are occurring?

I'll try to get that information tomorrow.


> Do the errors happen at the same time of day? Is there any pattern at all to the error times?

No, no periodicity was found. I was looking at events, times of day, and user actions.

> You've got Sphinx set up to use a UNIX socket rather than a TCP port - which should be fine! - but this is a new feature for Thinking Sphinx, so I'm not as experienced with debugging it. Perhaps it's worth trying TCP ports instead and see if that is more reliable?

Hmm... You may be right. We should try. But I can not yet understand whose problem it is: Sphinx, MySql or Thinking Sphinx.

**Comment by pat** [comment] 2018-07-15 09:54
> Hmm... You may be right. We should try. But I can not yet understand whose problem it is: Sphinx, MySql or Thinking Sphinx.

I feel like Sphinx is the likely culprit here (as much as any one thing can be blamed). Sphinx uses the MySQL connection protocol (and thus, Thinking Sphinx uses the mysql2 gem) - so the error is definitely related to Sphinx, not an actual MySQL database server. Thinking Sphinx is unlikely to have any issues with the connection - it's using mysql2, and I use it heavily myself (as do many others) and I feel it's very stable. All of that said - this situation is not one that comes up much, so it sounds like something odd is happening at some point somewhere 🤷‍♂️

**Comment by pat** [comment] 2018-09-01 02:56
Closing this issue as it's been a while since any updates. Still, feel free to ask further questions if it's still an ongoing problem!

**Closed by pat** 2018-09-01 02:56 UTC
