### ISSUE TITLE
Thinking Sphinx and CircleCI

### ISSUE THREAD

**Issue by kreopelle** [pat/thinking-sphinx#1156] opened 2019-12-10 23:45 UTC
I'm having trouble getting specs that run Thinking Sphinx 3.2.0 to work on CircleCI. The first Sphinx spec passes, and all subsequent specs fail. All Sphinx specs are passing locally.

The app I'm using is running Rails 5.1, Ruby 2.3.1, RSpec 3.8.

My Sphinx support file for RSpec looks like this: 

```
module SphinxHelpers
  def index
    ThinkingSphinx::Test.index
    # Wait for Sphinx to finish loading in the new index files.
    sleep 0.25 until index_finished?
  end

  def index_finished?
    Dir[Rails.root.join(ThinkingSphinx::Test.config.indices_location, '*.{new,tmp}*')].empty?
  end
end

RSpec.configure do |config|
  config.include SphinxHelpers, type: :feature

  config.before(:suite) do
    # Ensure sphinx directories exist for the test environment
    ThinkingSphinx::Test.init
    # Configure and start Sphinx, and automatically
    # stop Sphinx at the end of the test suite.
    ThinkingSphinx::Test.start_with_autostop
    ThinkingSphinx::Deltas.suspend!
  end

  config.after(:suite) do
    ThinkingSphinx::Test.stop
    ThinkingSphinx::Deltas.resume!
  end
end

```

Instead of a `before(:each)` setting for acceptance specs, I'm calling `index` in a `before` block on the specs where `sphinx: true`. 

Example: 

```
describe 'Product Search', type: :feature, sphinx: true do
  before { index }

  describe 'Product search from /products' do
    before(:each) do
      visit '/products'
      click_link 'Filter'
    end

    it 'finds all the products when no filters are selected', js: true do
      click_button 'Run Filters'
      expect(page).to have_content('2 products found for: All Products')
    end
  end
end
```

My current CircleCI config installs `sphinxsearch`:
```
      - run:
          name: Install sphinx dependencies
          command: sudo apt-get install sphinxsearch
```

And runs the tests through this command: 
```
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

            bundle exec rspec --format progress $TEST_FILES
```

Are there any additional steps that need to be taken to get Thinking Sphinx to run on CircleCI?

Any help would be greatly appreciated!

**Comment by pat** [comment] 2019-12-11 12:19
Hi Kayla,

I've not used TS with CircleCI yet, so I'm not entirely sure what the cause of the problem might be. Can you elaborate on the failing tests - in what way are they failing? Can they not connect to Sphinx? Can they connect but aren't returning the correct results? Or is it some other issue?

**Comment by kreopelle** [comment] 2019-12-12 00:38
Hi @pat

Thanks for your response!

The tests are failing in the same way they do without indexing (as if I commented out the `before {index}` block, so I don't think they're connecting to Sphinx at all. I am not getting any errors that specifically refer to Sphinx.

For example, the spec I referenced in my original comment fails with a message like this:
```
  1) Product search from /products finds all the products when no filters are selected
     Failure/Error: expect(page).to have_content('2 products found for: All Products')

expected to find text "2 products found for: All Products" in "All Products Search Results Filter 0 products found for: All Products There are no products"
```

**Comment by pat** [comment] 2019-12-12 13:00
Hmm. It sounds like Sphinx is running, and TS can talk to it, but the records aren't ending up in the database. Can you add `:verbose => true` as an argument to `ThinkingSphinx::Test.index` and see if that provides any clues? (The test output will get very noisy 😅). 

And I'm guessing you've got `use_transactional_fixtures` set to false, given the tests work fine locally… 🤔 Feels all rather mysterious to me, hoping those verbose indexer output logs provide a clue or two!

**Comment by kreopelle** [comment] 2019-12-12 19:07
What a great tip, I didn't know about that option on `ThinkingSphinx::Test.index`. And yes, `use_transactional_fixtures` is set to false.

Here's the output for one of the specs (they're all pretty similar): 

```
Sphinx 2.2.11-id64-release (95ae9a6)
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/home/circleci/repo/config/test.sphinx.conf'...
indexing index 'refinery_products_product_core'...
ERROR: index 'refinery_products_product_core': sql_fetch_row: Out of sort memory, consider increasing server sort buffer size.
total 0 docs, 0 bytes
total 0.004 sec, 0 bytes/sec, 0.00 docs/sec
indexing index 'refinery_recipes_recipe_core'...
collected 0 docs, 0.0 MB
total 0 docs, 0 bytes
total 0.002 sec, 0 bytes/sec, 0.00 docs/sec
indexing index 'refinery_community_post_core'...
collected 0 docs, 0.0 MB
total 0 docs, 0 bytes
total 0.002 sec, 0 bytes/sec, 0.00 docs/sec
indexing index 'desk_article_core'...
collected 0 docs, 0.0 MB
total 0 docs, 0 bytes
total 0.001 sec, 0 bytes/sec, 0.00 docs/sec
skipping non-plain index 'refinery_products_product'...
skipping non-plain index 'refinery_recipes_recipe'...
skipping non-plain index 'refinery_community_post'...
skipping non-plain index 'desk_article'...
total 3 reads, 0.000 sec, 0.0 kb/call avg, 0.0 msec/call avg
total 21 writes, 0.000 sec, 0.0 kb/call avg, 0.0 msec/call avg
rotating indices: successfully sent SIGHUP to searchd (pid=12516)
```

So perhaps it's something to do with `ERROR: index 'refinery_products_product_core': sql_fetch_row: Out of sort memory, consider increasing server sort buffer size.`? Do you see any clues?

**Comment by pat** [comment] 2019-12-14 05:34
Yeah, I think that error message is the cause as well.

From previous reports ([1](http://blog.aelogica.com/development/running-thinking-sphinx-with-mysql-and-postgres-on-osx-snow-leopard/), [2](https://groups.google.com/forum/#!topic/thinking-sphinx/PXfGGMJqmqc)) it looks like changing the database settings should help. Granted, I'm a little surprised this is cropping up given its in the test environment and I wouldn't expect much data, but perhaps the resources given to databases on CircleCI environments are super-limited? Or are you loading up a significant amount of records into the database for these tests?

**Comment by kreopelle** [comment] 2019-12-18 18:46
@pat - Thanks for those links! I'll try adjusting the database settings in the ways those articles suggest. I'm a little surprised too, it could be something related to CircleCI database environments. Less than 5 records should be created for each test that uses sphinx.

Our database is already setting `sort_buffer_size` to 2750000 for tests (though I'm not sure when that setting was made or why)

I'll let you know how it goes! Thank you for your help!!

**Comment by pat** [comment] 2020-04-24 08:55
This issue's been dormant for a while, so I'm going to close it just to keep things tidy - but if there's further questions around this topic, still feel free to comment here, and we can re-open if required :)

**Closed by pat** 2020-04-24 08:55 UTC

**Comment by pat** [comment] 2021-08-28 03:01
Ah, it does seem to be very similar. I don't mind if it stays here.

And just to clarify: are you using Thinking Sphinx v3.2.0 or v5.0.0? Also: I know you said the stacktrace comes from the `let`, which is probably not the cause, but can you share the trace anyway, along with the error? There may be clues in there that help (because right now, I have no idea what the problem is! 😅)

**Comment by ErinClaudio** [comment] 2021-08-30 15:17
Thank you again for your response

- I am currently running thinking-sphinx (5.0.0)

locally  - RSpec
- 344 examples, 4 failures

on CI - I have series of different failures 

- 12 failures that match the below Trackback

![Screen Shot 2021-08-30 at 11 12 31 AM](https://user-images.githubusercontent.com/20326770/131361836-b6e95e12-6844-48f2-9a78-6deb7651a318.png)

- 6  failures that match the below Trackback
![Screen Shot 2021-08-30 at 11 14 36 AM](https://user-images.githubusercontent.com/20326770/131362171-3bd4dc4d-fbce-4cec-a709-80133fb9eb02.png)
 failures that match the below Trackback

- 6  failures that match the below Trackback
![Screen Shot 2021-08-30 at 11 16 50 AM](https://user-images.githubusercontent.com/20326770/131362500-3d6c3c20-1148-427c-a5a6-bbe18164f75f.png)

**Comment by pat** [comment] 2021-08-31 07:04
Thanks for those details Erin. It looks like some further digging for details is required.

Firstly: those failing tests - is the missing content something that's driven by Sphinx? I'm presuming so. And so: can you confirm the data is being indexed reliably? The note about using `ThinkingSphinx::Test.index :verbose => true` in the early discussion in this thread could be a good place to start. It does mean that your test output will get quite noisy though - if there's a test that's _always_ failing in CI, I would recommend creating a new branch, and having CI run just that branch (with the verbose indexing) to see if the issue can be found more directly.

Also, you mentioned some tests fail locally for you - is there any overlap between tests that fail on CI that are search related, and that _also_ fail on your own machine?
