### ISSUE TITLE
Thinking Sphinx freezes after cap production thinking_sphinx:restart command

### ISSUE THREAD

**Issue by sunchess** [pat/thinking-sphinx#1234] opened 2022-09-27 12:37 UTC
Hi guys, I'm trying to config TS for working with capistrano and seems there is a bug. The command just freezes after `restart`.

My env:
 - ruby 3.1.1
 - rails 6.1.4.1
 - Sphinx 3.4.1 (commit efbcc65)
 
The command log
```bash
 % cap production thinking_sphinx:restart
Please enter branch (main):
rvm 1.29.12 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
ruby-3.1.1
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux]
00:00 thinking_sphinx:restart
      01 ~/.rvm/bin/rvm 3.1.1@youecho do bundle exec rake ts:stop
      01 Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
      01 [Tue Sep 27 12:32:10.993 2022] [796888] using config file '/home/deploy/apps/youecho/shared/config/production.sphinx.conf'...
      01 [Tue Sep 27 12:32:10.994 2022] [796888] stop: successfully sent SIGTERM to pid 795949
      01 Sphinx 3.4.1 (commit efbcc65)
      01 Copyright (c) 2001-2021, Andrew Aksyonoff
      01 Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
      01
      01 Stopped searchd daemon (pid: 795949).
    ✔ 01 deploy@94.103.92.114 5.519s
      02 ~/.rvm/bin/rvm 3.1.1@youecho do bundle exec rake ts:configure
      02 Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
      02 Generating configuration to /home/deploy/apps/youecho/shared/config/production.sphinx.conf
    ✔ 02 deploy@94.103.92.114 2.221s
      03 ~/.rvm/bin/rvm 3.1.1@youecho do bundle exec rake ts:start
      03 Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
      03 [Tue Sep 27 12:32:19.048 2022] [797485] using config file '/home/deploy/apps/youecho/shared/config/production.sphinx.conf'...
      03 Sphinx 3.4.1 (commit efbcc65)
      03 Copyright (c) 2001-2021, Andrew Aksyonoff
      03 Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
      03
      03 listening on 127.0.0.1:9312
      03 Sphinx 3.4.1 (commit efbcc65)
      03 Copyright (c) 2001-2021, Andrew Aksyonoff
      03 Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
      03
      03 precaching index 'card_core'
      03 precaching index 'tags_user_core'
      03 Sphinx 3.4.1 (commit efbcc65)
      03 Copyright (c) 2001-2021, Andrew Aksyonoff
      03 Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
      03
      03 Started searchd successfully (pid: 797488).
```
Can you help me?

**Comment by pat** [comment] 2022-12-30 02:19
Hi @sunchess - very sorry for the slow response, but wondering if you made any progress on this? I'm afraid I don't have any inspiration for what the cause may be, though I'm a bit out of practice with Capistrano.

**Comment by pat** [comment] 2024-07-07 08:50
Closing this ticket as it's been 18 months (granted, that's not aided by my previous slow response)

**Closed by pat** 2024-07-07 08:50 UTC
