### ISSUE TITLE
Wildcard search does not find exactly matching text

### ISSUE THREAD

**Issue by airblade** [pat/thinking-sphinx#909] opened 2015-04-28 15:12 UTC
Hi Pat,

I'm not sure whether this concerns Thinking Sphinx, Riddle or Sphinx itself so I hope you don't mind my asking here :)

I have an indexed record with a field consisting of the text `Tiny Cubic Zirconia Round Pendant on Gold Chain`.

When I search for `Tiny Cubic Zirconia Round Pendant on Gold Chain` TS finds the record as expected.

When I enclose the text in quotation marks (`"Tiny Cubic Zirconia Round Pendant on Gold Chain"`) and run it through `ThinkingSphinx::Query.wildcard` along the way, TS does find the record – as expected.  (The resulting query is `\"Tiny Cubic Zirconia Round Pendant on Gold Chain\"`.)

However when I search for the text without quotation marks, wildcarding it along the way, TS doesn't find the record – to my surprise.  (The wildcarding of the unquoted text results in `*Tiny* *Cubic* *Zirconia* *Round* *Pendant* *on* *Gold* *Chain*`.)

I have `min_prefix_len: 4` in my config and a wildcarded search for `zirc` does indeed find my record, so the wildcard / prefix stuff is generally working.

Why doesn't the unquoted text, wildcarded, get a hit?

**Comment by airblade** [comment] 2015-04-28 15:13
FWIW I'm on TS 3.1.2, Riddle 1.5.11, Sphinx 2.2.4.

**Comment by pat** [comment] 2015-04-29 02:04
Hmmm... odd. What happens if you limit the search query to `Tiny Cubic Zirconia Round Pendant`, with wildcarding? Wondering if *on* is the cause because min_prefix_len is 4 (which would be annoying behaviour, but just guesswork at this point in time).

**Comment by airblade** [comment] 2015-04-29 08:54
Good guess – these both work, with wildcarding:

- `Tiny Cubic Zirconia Round Pendant Gold Chain`
- `Tiny Cubic Zirconia Round Pendant "on" Gold Chain`

I can't quite figure out whether this is expected behaviour from Sphinx or a bit of a bug.

TS's wildcarding both prepends and appends a star.  Assuming Sphinx is configured to index prefixes, when the query reaches Sphinx does Sphinx ignore the leading star (because it's not in the `charset_table`) but pay attention to the trailing star (because prefixes are configured)?

**Comment by airblade** [comment] 2015-04-29 09:13
Further testing reveals a three letter word doesn't need to be quoted...

**Comment by pat** [comment] 2015-04-29 12:27
Three letter words are fine? Well that just removes any consistency :| Not that the behaviour was that great anyway... do you find it always screws things up with any two-letter word?

As a potential workaround, you could take the TS Wildcard code, adapt it so it just has the suffixed wildcard, instead of suffix and prefix? The change should be pretty obvious :)
https://github.com/pat/thinking-sphinx/blob/master/lib/thinking_sphinx/wildcard.rb

Granted, no idea if that'll make these queries behave correctly, but another data point wouldn't hurt.

**Comment by airblade** [comment] 2015-04-29 13:36
All the two letter words I've tried have failed to match.

When I modify the TS Wildcard code to append, but not prepend, the wildcard, three letter words fail to match.

Sphinx seems to be changing its search behaviour based on the presence or absence of a prepended star – which is weird because the star isn't in my `charset_table` and therefore should be treated as a word separator and ignored.

I don't understand it at all :/

Here's my workaround which passes my tests:

```diff
diff --git a/lib/thinking_sphinx/wildcard.rb b/lib/thinking_sphinx/wildcard.rb
index 57e6b87..777df0a 100644
--- a/lib/thinking_sphinx/wildcard.rb
+++ b/lib/thinking_sphinx/wildcard.rb
@@ -1,5 +1,6 @@
 class ThinkingSphinx::Wildcard
   DEFAULT_TOKEN = /\p{Word}+/
+  MIN_PREFIX_LEN = ThinkingSphinx::Configuration.instance.settings['min_prefix_len'] || 1000
 
   def self.call(query, pattern = DEFAULT_TOKEN)
     new(query, pattern).call
@@ -20,7 +21,7 @@ class ThinkingSphinx::Wildcard
       # E.g. "foo bar", with quotes
       is_quote    = proper[/^".*"$/]
       has_star    = post[/\*$/] || pre[/^\*/]
-      if is_operator || is_quote || has_star
+      if is_operator || is_quote || has_star || proper.length < MIN_PREFIX_LEN - 1
         proper
       else
         "*#{proper}*"
```

If you drop the `*` wildcard prefix you need to also drop the `- 1` in the comparison.

**Comment by pat** [comment] 2015-05-01 03:15
I kinda like this approach, though there are issues - would need to handle both infixes and prefixes (not too difficult), but also some indices may have infixes enabled, others may have prefixes enabled - the overall setting is not a reliable indicator. And the wildcard code has *no* context about which index you're dealing with (and I rather like that simplicity).

Still, something to ponder...

**Comment by airblade** [comment] 2015-05-05 14:39
You're right, it's far from a general solution.

It would be nice to have a better idea what's going on with Sphinx.  I tried to come up with a minimal reproduction of the problem using SphinxQL so I could open a ticket on Sphinx's bug tracker – but I couldn't figure out how to run any SphinxQL at all.  I started a mysql console connecting to port 9306 [as per the docs](http://sphinxsearch.com/docs/archives/2.2.4/sphinxql.html) but it rejected all my SphinxQL efforts...

These Sphinx bug reports sound related: [#637](http://sphinxsearch.com/bugs/view.php?id=637), [#1721](http://sphinxsearch.com/bugs/view.php?id=1721).  Unfortunately they fizzled out...

**Comment by pat** [comment] 2015-05-06 00:29
Try `mysql --host 127.0.0.1 --port 9306` - if the host isn't specified, and MySQL on your machine is configured to use a socket by default, then the command-line tool actually defaults to the socket (thus, connecting to MySQL proper) instead of Sphinx, ignoring the lone port argument. There is a flag for saying "Use the port, not the socket", but I never remember what that is :)

**Comment by airblade** [comment] 2015-05-08 10:22
Thanks, that works :)  I'll update here when I get a chance to pursue this.

**Comment by pat** [comment] 2016-03-26 00:51
Andy, going to close this issue - presuming either it was solved, or you found a workaround, or even switched to something else. I know it's almost been a year, but if you did find a solution, it'd be great to hear more about it :)

**Closed by pat** 2016-03-26 00:51 UTC

**Comment by airblade** [comment] 2016-03-29 16:50
Pat, sorry for leaving this hanging for so long.  I pursued it further, didn't find out anything useful, got distracted and...here we are :/

I've had the workaround above in production all this time and I haven't received any bug reports.  It's not generally applicable, as you said, but it works for my situation.

Thanks for your help!
