### ISSUE TITLE
Riddle::CommandFailedError (Sphinx command failed to execute)

### ISSUE THREAD

**Issue by sesaretah** [pat/thinking-sphinx#1036] opened 2016-12-31 05:31 UTC
Hi, I am using ts version 3.1.3 with Sphinx ver 2.2.11-id64-release on Ubuntu 14.04.4 LTS on Rails 4.2

Running rake ts:rebuild works perfect however, production server have the following error log:

> F, [2016-12-31T08:50:55.798962 #2042] FATAL -- :
Riddle::CommandFailedError (Sphinx command failed to execute):
  app/controllers/profiles_controller.rb:69:in `block in create'
  app/controllers/profiles_controller.rb:68:in `create'

p.s. I am using delta indexing on profile model 
commands 

> searchd -v

> rake ts:rebuild

works perfectly

Any idea what can cause the error ?

**Comment by pat** [comment] 2016-12-31 05:47
I don't suppose you can get a full stack trace of the error? In particular, any lines referencing either TS or the Riddle gem.

Also, I'd recommend upgrading TS to v3.3.0, which makes better use of the latest Riddle release and the error messages may be a little more helpful then. I don't believe there are any breaking changes, but it's definitely worth reading the release notes for [v3.1.4](https://github.com/pat/thinking-sphinx/releases/tag/v3.1.4), [v3.2.0](https://github.com/pat/thinking-sphinx/releases/tag/v3.2.0) and [v3.3.0](https://github.com/pat/thinking-sphinx/releases/tag/v3.3.0).

But more generally: are you using any background worker to process the deltas? Or are you using the default approach? Have deltas worked in the past, or is this the first time you're using them?

**Comment by pat** [comment] 2017-04-21 12:56
It's been a few months since this issue was last referenced, so I'm going to close it. Feel free to discuss the issue further, though - and if we need to, I can always re-open it.

**Closed by pat** 2017-04-21 12:56 UTC

**Comment by keithmattix** [comment] 2017-09-28 20:24
I'm having this error when running my tests. Here's the stack trace:

> EXCEPTION: Sphinx command failed to execute
BACKTRACE: /Users/keith/.rvm/gems/ruby-2.4.2/gems/riddle-2.2.0/lib/riddle/execute_command.rb:23:in `call'
/Users/keith/.rvm/gems/ruby-2.4.2/gems/riddle-2.2.0/lib/riddle/execute_command.rb:5:in `call'
/Users/keith/.rvm/gems/ruby-2.4.2/gems/riddle-2.2.0/lib/riddle/controller.rb:29:in `index'
/Users/keith/.rvm/gems/ruby-2.4.2/gems/thinking-sphinx-3.4.1/lib/thinking_sphinx/controller.rb:8:in `block (2 levels) in index'
/Users/keith/.rvm/gems/ruby-2.4.2/gems/thinking-sphinx-3.4.1/lib/thinking_sphinx/guard/files.rb:14:in `call'
/Users/keith/.rvm/gems/ruby-2.4.2/gems/thinking-sphinx-3.4.1/lib/thinking_sphinx/guard/files.rb:3:in `call'
/Users/keith/.rvm/gems/ruby-2.4.2/gems/thinking-sphinx-3.4.1/lib/thinking_sphinx/controller.rb:7:in `block in index'
/Users/keith/.rvm/gems/ruby-2.4.2/gems/thinking-sphinx-3.4.1/lib/thinking_sphinx/indexing_strategies/all_at_once.rb:5:in `call'
/Users/keith/.rvm/gems/ruby-2.4.2/gems/thinking-sphinx-3.4.1/lib/thinking_sphinx/controller.rb:6:in `index'
/Users/keith/.rvm/gems/ruby-2.4.2/gems/thinking-sphinx-3.4.1/lib/thinking_sphinx/deltas/index_job.rb:7:in `perform'

**Comment by pat** [comment] 2017-09-29 03:12
Hi Keith,

I'm not sure why this is happening, but could you try rescuing the `Riddle::CommandFailedError` error, and then outputting the `command_result` value from it? It may hold more clues. So, something like the following in your test:

```ruby
begin
  # do the things that invoke the delta indexing
rescue Riddle::CommandFailedError => error
  puts "Command Result: #{error.command_result}"
end
```

**Comment by keithmattix** [comment] 2017-09-29 15:17
Ah, thank you; I've found the suspicious index. I'm going through a rails upgrade to 5.1, so I'm going to check my index definition for any breaking changes

**Comment by karthiksridhar** [comment] 2018-01-12 20:23
Hi Pat,
I am facing the same issue right now. I am using delta indexing using DelayedDelta. The thinking sphinx version I am using is 3.4.2.

**Comment by karthiksridhar** [comment] 2018-01-12 20:25
This is the stack trace

rake aborted!
TypeError: no implicit conversion from nil to integer
/usr/local/rvm/gems/ruby-2.3.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/commands/base.rb:33:in `exit'
/usr/local/rvm/gems/ruby-2.3.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/commands/base.rb:33:in `handle_failure'
/usr/local/rvm/gems/ruby-2.3.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/commands/base.rb:11:in `rescue in call_with_handling'
/usr/local/rvm/gems/ruby-2.3.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/commands/base.rb:9:in `call_with_handling'
/usr/local/rvm/gems/ruby-2.3.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/commands/base.rb:5:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/interfaces/sql.rb:31:in `index'
/usr/local/rvm/gems/ruby-2.3.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/tasks.rb:86:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
Riddle::CommandFailedError: Sphinx command failed to execute
/usr/local/rvm/gems/ruby-2.3.1/gems/riddle-2.2.0/lib/riddle/execute_command.rb:23:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/riddle-2.2.0/lib/riddle/execute_command.rb:5:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/riddle-2.2.0/lib/riddle/controller.rb:29:in `index'
/usr/local/rvm/gems/ruby-2.3.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/controller.rb:8:in `block (2 levels) in index'
/usr/local/rvm/gems/ruby-2.3.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/guard/files.rb:14:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/guard/files.rb:3:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/controller.rb:7:in `block in index'
/usr/local/rvm/gems/ruby-2.3.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/indexing_strategies/all_at_once.rb:5:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/controller.rb:6:in `index'
/usr/local/rvm/gems/ruby-2.3.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/commands/index.rb:3:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/commands/base.rb:9:in `call_with_handling'
/usr/local/rvm/gems/ruby-2.3.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/commands/base.rb:5:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/interfaces/sql.rb:31:in `index'
/usr/local/rvm/gems/ruby-2.3.1/gems/thinking-sphinx-3.4.2/lib/thinking_sphinx/tasks.rb:86:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => ts:rebuild => ts:sql:index
(See full trace by running task with --trace)

The Sphinx indexing command failed:
  Command: indexer --config "/var/www/edwave/config/production.sphinx.conf" --all
  Status:
  Output:  See above

**Comment by pat** [comment] 2018-01-13 00:14
@karthiksridhar that stack trace has helped me find minor bugs in both Riddle and Thinking Sphinx - though I'm not sure what the specific problem you're facing is. If possible, can you use the latest from the develop branch of both gems? Any error messages should be more useful then.

```ruby
gem "riddle", "~> 2.2",
  :git    => "https://github.com/pat/riddle.git",
  :branch => "develop",
  :ref    => "3ac74fc3f1"
gem "thinking-sphinx", "~> 3.4"
  :git    => "https://github.com/pat/thinking-sphinx.git",
  :branch => "develop",
  :ref    => "e1af0aa25f"
```

**Comment by karthiksridhar** [comment] 2018-01-13 03:54
Sure. I'll do that. This error has occurred in the production environment unfortunately. So it is quite urgent. Thanks a lot for your prompt response. I hope we can fix this as soon as possible.

**Comment by karthiksridhar** [comment] 2018-01-13 04:47
@pat It is working perfectly now. Indexing went through successfully. Thanks a lot!

**Comment by karthiksridhar** [comment] 2018-01-13 08:02
@pat Indexing went through successfully. However, the delta indexing bit is not working properly. I am using DelayedDelta for delta indexing. Jobs are even successfully created on delayed_job. However, instead of creating delta indexes, the following message is shown on doing rake jobs:workoff. It never says "Indexing". It only say deleted "_core" index. Is this related to your change? Or is it independent? I ask this because you have asked questions specific to delta indexing in earlier parts of this thread. As a consequence 

[Worker(test pid:7041)] Starting job worker
[Worker(host:test pid:7041)] Job Thinking Sphinx: Mark 9651715 in exact_uploaded_resume_core as deleted (id=608406) (queue=default) RUNNING
[Worker(host:test pid:7041)] Job Thinking Sphinx: Mark 9651715 in exact_uploaded_resume_core as deleted (id=608406) (queue=default) COMPLETED after 0.6358
[Worker(host:test pid:7041)] Job Thinking Sphinx: Process resume_email_delta (id=608407) (queue=default) RUNNING
[Worker(host:test pid:7041)] Job Thinking Sphinx: Process resume_email_delta (id=608407) (queue=default) COMPLETED after 0.0630
[Worker(host:test pid:7041)] Job Thinking Sphinx: Mark 1453138 in resume_email_core as deleted (id=608408) (queue=default) RUNNING
[Worker(host:test pid:7041)] Job Thinking Sphinx: Mark 1453138 in resume_email_core as deleted (id=608408) (queue=default) COMPLETED after 0.0045
[Worker(host:test pid:7041)] Job Thinking Sphinx: Mark 9651715 in exact_uploaded_resume_core as deleted (id=608409) (queue=default) RUNNING
[Worker(host:test pid:7041)] Job Thinking Sphinx: Mark 9651715 in exact_uploaded_resume_core as deleted (id=608409) (queue=default) COMPLETED after 0.0052
[Worker(host:test pid:7041)] Job Thinking Sphinx: Mark 9651715 in exact_uploaded_resume_core as deleted (id=608410) (queue=default) RUNNING
[Worker(host:test pid:7041)] Job Thinking Sphinx: Mark 9651715 in exact_uploaded_resume_core as deleted (id=608410) (queue=default) COMPLETED after 0.0059
[Worker(host:test pid:7041)] Job Thinking Sphinx: Mark 1453138 in resume_email_core as deleted (id=608411) (queue=default) RUNNING
[Worker(host:test pid:7041)] Job Thinking Sphinx: Mark 1453138 in resume_email_core as deleted (id=608411) (queue=default) COMPLETED after 0.0062
[Worker(host:test pid:7041)] Job Thinking Sphinx: Mark 1453138 in resume_email_core as deleted (id=608412) (queue=default) RUNNING
[Worker(host:test pid:7041)] Job Thinking Sphinx: Mark 1453138 in resume_email_core as deleted (id=608412) (queue=default) COMPLETED after 0.0034
[Worker(host:test pid:7041)] 7 jobs processed at 7.9107 j/s, 0 failed
[Worker(host:test pid:7041)] No more jobs available. Exiting

**Comment by pat** [comment] 2018-01-13 11:44
@karthiksridhar am glad at least part of this is working as expected!

Regarding the delayed jobs - every time you make a change or add a new record, two jobs are queued. One is for processing the delta index, the other is for marking the core record as deleted (so the old values don't return the record in searches).

However, as you've noted, you're mostly only seeing the second of those jobs running (though there is one call to `resume_email_delta` in your logs!). Are you seeing the delta indices being processed more often now?

Also, can you do an `ls -al` in your indices directory and check whether there are any files named `ts-INDEXNAME.tmp` in there? These [guard files](https://freelancing-gods.com/thinking-sphinx/rake_tasks.html#index-guard-files) are created as each index is processed (and then deleted straight after) to avoid concurrent indices - I'm wondering if some got stuck from the crashes you were seeing earlier. You can safely remove them.

**Comment by karthiksridhar** [comment] 2018-01-13 16:27
Delta indices are not being processed more often now. It happens as often as changes to the database happen. I think that part is fine. I'm not sure why the "processing delta index" part is not working.

I checked for ts-INDEXNAME.tmp. It was not present. 

I have switched to normal non-asynchronous delta indexing now since it is in production. That is working fine as expected. Ideally I would like to switch back to DelayedDelta. Any other ideas on what might be wrong?

**Comment by pat** [comment] 2018-01-14 01:37
Hmm, not entirely sure what the cause of the problem is.

Are there any jobs hanging around in your `delayed_jobs` table related to delta indexing?

**Comment by pat** [comment] 2018-01-14 01:39
To continue with my previous comment… ts-delayed-delta won't queue up a new delta job if one already exists:
https://github.com/pat/ts-delayed-delta/blob/master/lib/thinking_sphinx/deltas/delayed_delta.rb#L32

But there are some conditions there that should ensure only active jobs are checked. I'm wondering if there's been some change to DJ or if something else has stopped jobs from being enqueued.

**Comment by karthiksridhar** [comment] 2018-02-04 00:22
Hi Pat,
I'm sorry I didn't get back immediately. I had some other things to attend to. The update on this issue is that I have gone back to a more stable version of riddle(1.5.10). I am now using thinking sphinx 3.1.0 which works with riddle 1.5.10. My indexing on production went through successfully after that. So, there seems to be some bug because of changes between riddle 1.5.10 and 2.2 I guess.

I was not able to replicate the issue on my local machine. So I just thought I would let you know. Riddle is the culprit. Also, it did not give a descriptive error message. It just said Command failed to execute. Hope this helps. Let me know if I can help in any other way.

**Comment by xtrasimplicity** [comment] 2018-02-26 20:42
I'm having much the same issue with TS 3.4.2 (riddle 2.3.0).

```
$ bundle exec rake ts:restart
Sphinx 3.0.1 (commit 7fec4f6)
Copyright (c) 2001-2017, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file 'shared/sphinx/development.sphinx.conf'...
WARNING: key 'docinfo' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'docinfo' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'docinfo' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'docinfo' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: key 'docinfo' was permanently removed from Sphinx configuration. Refer to documentation for details.
WARNING: 17 more warnings skipped.
stop: successfully sent SIGTERM to pid 19257

The Sphinx stop command failed:
  Command: searchd --pidfile --config "shared/sphinx/development.sphinx.conf" --stopwait
  Status:
  Output:  See above

There may be more information about the failure in log/sphinx.log.
rake aborted!
TypeError: no implicit conversion from nil to integer
/home/andrew/.rbenv/versions/2.1.3/bin/bundle:23:in `load'
/home/andrew/.rbenv/versions/2.1.3/bin/bundle:23:in `<main>'
Riddle::CommandFailedError: Sphinx command failed to execute
/home/andrew/.rbenv/versions/2.1.3/bin/bundle:23:in `load'
/home/andrew/.rbenv/versions/2.1.3/bin/bundle:23:in `<main>'
Tasks: TOP => ts:restart => ts:stop
(See full trace by running task with --trace)
```
The log file is surprisingly empty:
```
# log/sphinx.log
[Tue Feb 27 07:34:49.538 2018] [15217] watchdog: main process 15218 forked ok
[Tue Feb 27 07:34:49.539 2018] [15218] listening on 127.0.0.1:9312
[Tue Feb 27 07:34:49.590 2018] [15218] WARNING: No extra index definitions found in data folder
[Tue Feb 27 07:34:49.591 2018] [15218] accepting connections
[Tue Feb 27 07:34:49.591 2018] [15230] prereading 22 indexes
[Tue Feb 27 07:34:49.591 2018] [15230] prereaded 22 indexes in 0.000 sec
```
lsof shows that sphinx actually _was_ successfully restarted, and I can confirm that TS callbacks etc still work correctly.
```
$ lsof -i :9312
COMMAND   PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
searchd 15218 andrew    7u  IPv4 107732      0t0  TCP localhost:sphinxapi (LISTEN)
```

My production environment (same version of Ruby, TS, Sphinx and Riddle) has exactly the same issue, so it may well be an incompatibility with the version of Ruby that I'm running? (I'm gradually upgrading, but it is a fairly lengthy process.)

For the moment, it isn't the end of the world, but it would be nice to be able to start Sphinx from a Procfile without having to ignore the exit code. :)

Any ideas?

**Comment by xtrasimplicity** [comment] 2018-02-27 21:05
It looks like my issue is caused by Sphinx itself, not TS, as Sphinx has a segmentation fault and crashes. The daemon (running on ports 9312 and 9306) remains active.
```
c$ searchd --pidfile --config "shared/sphinx/development.sphinx.conf"
Sphinx 3.0.1 (commit 7fec4f6)
Copyright (c) 2001-2017, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)

listening on all interfaces, port=9312
listening on all interfaces, port=9306
WARNING: No extra index definitions found in data folder
Segmentation fault (core dumped)
```
I'll keep looking. :)

**Comment by pat** [comment] 2018-03-01 00:50
Hmm, wonder if it's a change in behaviour with Sphinx 3.0.1? 3.0.2 was just released a few days ago, maybe it's worth giving that a shot and seeing if it behaves the same way?

**Comment by xtrasimplicity** [comment] 2018-03-01 01:15
Thanks @pat. I've checked version 3.0.2 (and the glibc 2.12 version, as my dev machine is running on Fedora 26) to no avail. When I get another chance I'll run strace/gdb against it again to see if I can work out what is going on.

Thanks once again!

**Comment by pat** [comment] 2018-03-01 05:49
Definitely sounds like a Sphinx issue (Riddle uses the exit status to determine whether there's a problem) - though the seg fault you shared in the latest output wasn't in your previous one? The source for the v3 releases of Sphinx aren't public (yet? ever? 🤷‍♂️), so that's another challenge for debugging…
